### ISSUE TITLE
make fails with aclocal-1.15

### ISSUE THREAD

**Issue by godot11** [scottdraves/flam3#14]
Running `./configure` works, but then `make` fails with the following error:
```
ezio@Cantabury ~/Downloads/elsheep/flam3 $ make
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.14 -I m4
/bin/bash: aclocal-1.14: command not found
Makefile:424: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127

```
Changing `am__api_version='1.15'` in the `configure` script does not affect this.
I found this issue on Linux Mint 18.2.

**Comment by toadkicker** [comment]
I fixed this by running these commands:

```
make clean
libtoolize
automake --add-missing
autoconf
./configure
make
```

**Comment by sampoz** [comment]
Fixed this by changing Makefile lines about ACLOCAL and AUTOMAKE:
 
ACLOCAL = aclocal-1.14    # -> 1.15  
AUTOMAKE = automake-1.14  # -> 1.15  

Found this fix from [here](https://blog.openbloc.fr/compiling-electric-sheep-on-ubuntu-linux-17-10/#2buildflam3). I am running mint 18 ( ubuntu xenial ).

**Comment by adeleglise** [comment]
For me the solution provided by @toadkicker is working. Using Ubuntu 17.10.
