### ISSUE TITLE
Unable to 'make' flam3

### ISSUE THREAD

**Issue by nickshanks347** [scottdraves/flam3#17]
`./configure` runs successfully
I get this error upon running 'make':
`CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.14 -I m4
/bin/bash: aclocal-1.14: command not found
Makefile:424: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127`

I'm running Ubuntu 17.10

**Comment by EReckase** [comment]
Could be related to https://github.com/scottdraves/flam3/issues/14.
