### ISSUE TITLE
Trying to compile with MS Visual Studio 2017

### ISSUE THREAD

**Issue by dfkettle** [scottdraves/flam3#28]
Has anyone been able to compile flam3 with MS Visual Studio 2017? It seems the format of the project files used by VS has changed. When I tried to open the project, VS attempted to upgrade the format, but it didn't seem to work, saying one or more of the files were corrupted.

Maybe it would be easier to compile with Cygwin or MINGW, using the Linux makefile. Is there a recommended way to compile for Windows?

Thanks.

**Comment by EReckase** [comment]
That's an excellent question. I haven't compiled the flam3 source on windows in a really, really, REALLY long time.

**Comment by dfkettle** [comment]
Is anybody still supporting it? There doesn't seem to be a lot of activity
here.

**Comment by EReckase** [comment]
There's not currently much active development with the flam3 engine itself; @scottdraves might have more news about electric sheep tho.

**Comment by dfkettle** [comment]
I gave up trying to compile with MS Visual Studio. Going to try compiling with Msys2.
